// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAcD5wlOzsBSzYSqcWQKACd2PS2ZfYKXs',
    appId: '1:584627694074:web:24bb8003f1e43cfa115c43',
    messagingSenderId: '584627694074',
    projectId: 'chatapp2-a217f',
    authDomain: 'chatapp2-a217f.firebaseapp.com',
    storageBucket: 'chatapp2-a217f.appspot.com',
    measurementId: 'G-QXQRTTJLQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2p0r4d0VugiTJzySbSOomvuTikwtfTs0',
    appId: '1:584627694074:android:43e1a13057945673115c43',
    messagingSenderId: '584627694074',
    projectId: 'chatapp2-a217f',
    storageBucket: 'chatapp2-a217f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0y3fSdjBNb4sL7Z0f_wwgZp6QNbcb-Jw',
    appId: '1:584627694074:ios:6618e94113be85c2115c43',
    messagingSenderId: '584627694074',
    projectId: 'chatapp2-a217f',
    storageBucket: 'chatapp2-a217f.appspot.com',
    iosClientId: '584627694074-tophcl0qksbv20rluljk1q4vlc7flse2.apps.googleusercontent.com',
    iosBundleId: 'com.chatapp.v1.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0y3fSdjBNb4sL7Z0f_wwgZp6QNbcb-Jw',
    appId: '1:584627694074:ios:6618e94113be85c2115c43',
    messagingSenderId: '584627694074',
    projectId: 'chatapp2-a217f',
    storageBucket: 'chatapp2-a217f.appspot.com',
    iosClientId: '584627694074-tophcl0qksbv20rluljk1q4vlc7flse2.apps.googleusercontent.com',
    iosBundleId: 'com.chatapp.v1.chatapp',
  );
}
